:verbose: false
:concurrency: 5
:timeout: 25
:max_retries: 3

:queues:
  - default

:scheduler:
  :schedule:
    invitation_job:
      cron: "*/1 * * * *" # Runs every minute
      class: InvitationJob
      queue: default
