:verbose: false
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:timeout: 25

:scheduler:
  :schedule:
    invitation_job:
      every: "3m"
      class: InvitationJob
      description: "Send invitation email to invitees 3 minutes before the test starts"
