:verbose: false
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:timeout: 25

:scheduler:
  :schedule:
    invitation_job:
      every: "5m"
      class: InvitationJob
      description: "Send invitation email to invitees 5 minutes before the test starts"
